version: '3'
services:
    node-ok-dev:
        image: registry.cn-shenzhen.aliyuncs.com/yxw-docker/node-10.15.3-schedulerx:latest
        container_name: node-ok-dev
        hostname: node-ok-dev
        network_mode: bridge
        ports:
            - "9300:9300"
        working_dir: /source/bs-ccr-node-okex
        external_links:
          - redis-dev:redis-dev
        volumes:
            - /source/bs-ccr-node-okex:/source/bs-ccr-node-okex
            - /Users/sivan/Library/Caches/Yarn/v4:/usr/local/share/.cache/yarn/v4
        environment:
            ENV_GROUP_ID: bs-ccr-node
            ENV_ENDPOINT: addr-sz-internal.edas.aliyun.com
            ENV_NAMESPACE: 3b301850-faa2-4748-b962-f499c5e24c97
            ENV_ALIYUN_ACCESS_KEY: LTAI4FipRPK3htsT54j4ahZa
            ENV_ALIYUN_SECRET_KEY: Oz9fRDjndnfTWMlBCcw8mVkm2Z0xQV
        command: ["/bin/sh", "-c", "/opt/schedulerx_conf.sh && yarn install && yarn dev"]
